module SkelAct where

-- Haskell module generated by the BNF converter

import AbsAct
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transAct :: Act -> Result
transAct x = case x of
  Main headers -> failure x
transHeader :: Header -> Result
transHeader x = case x of
  Behave ident1 ident2 -> failure x
  Interf ident decls -> failure x
  Quant tdecls -> failure x
  Iff bexps -> failure x
  IffIn type_ exps -> failure x
  If bexps -> failure x
  StorageH updates -> failure x
  Return exp -> failure x
transUpdate :: Update -> Result
transUpdate x = case x of
  Change storage exp -> failure x
  Const storage -> failure x
  OChange storage exp1 exp2 -> failure x
  OConst storage exp -> failure x
transStorage :: Storage -> Result
transStorage x = case x of
  Map ident lookups -> failure x
  Struct storage ident -> failure x
transLookup :: Lookup -> Result
transLookup x = case x of
  Look ident -> failure x
transBExp :: BExp -> Result
transBExp x = case x of
  BAnd bexp1 bexp2 -> failure x
  BOr bexp1 bexp2 -> failure x
  BEq exp1 exp2 -> failure x
  BNeq exp1 exp2 -> failure x
  BLEQ exp1 exp2 -> failure x
  BLE exp1 exp2 -> failure x
  BGEQ exp1 exp2 -> failure x
  BGE exp1 exp2 -> failure x
  BTrue -> failure x
  BFalse -> failure x
transExp :: Exp -> Result
transExp x = case x of
  EAdd exp1 exp2 -> failure x
  ESub exp1 exp2 -> failure x
  EMul exp1 exp2 -> failure x
  EDiv exp1 exp2 -> failure x
  EInt integer -> failure x
  EVar storage -> failure x
transDecl :: Decl -> Result
transDecl x = case x of
  Dec type_ ident -> failure x
transTDecl :: TDecl -> Result
transTDecl x = case x of
  TDec ident type_ -> failure x
transType :: Type -> Result
transType x = case x of
  Type_uint -> failure x
  Type_int -> failure x
  Type_uint256 -> failure x
  Type_int256 -> failure x
  Type_uint126 -> failure x
  Type_int126 -> failure x
  Type_uint8 -> failure x
  Type_int8 -> failure x
  Type_address -> failure x
  Type_bytes32 -> failure x
  Type_bool -> failure x

